version: "3.7"

services:
  app:
    build: .
    command: node index.js
    # ports:
    #   - 3000:3000
    volumes:
      - .:/srv/app
      # Declare a named volume `app_node_modules` here and at the top level
      - app_node_modules:/srv/app/node_modules

volumes:
  # Declare a named volume `app_node_modules` here and at the top level
  app_node_modules:
